# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b140a4d318117df05a11bdfa913290806bc79566014be8d3f7ca6f671412292031e5db95062ea0b81cb825de1ec32228b51fc95a425d92a97fdab08d329a7d2

test:
  secret_key_base: 871025b3b4b9d0a4c3d3729f36f06423c9c85dd8be4c6d92166802a54c518c1da7c291f2881ee73206efad56ae436468e82d2fdacdf4be7f28256b6e754c1470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
